# Config file for automatic testing at travis-ci.org
sudo: false

language: python
cache: pip

env:
- FLASK_APP=app.py FLASK_DEBUG=0 FLASK_ENV=production DATABASE_URL="sqlite:////tmp/dev.db"

python:
  - "3.7"

install:
  - cd app
  - pip install -r requirements/dev.txt
  - npm install

before_script:
  - npm run lint
  - npm run build

script:
  - py.test --cov-report=xml --cov=personalWebsiteFlask tests/

after_success:
  - codecov