version: '3.3'
services:
  webpack:
    container_name: webpack
    build: ./webpack
    volumes: 
      - webpackBuild:/static/build
    ports:
      - "2992:2992"
    networks:
      - container-network
  app:
    container_name: app
    build: ./app
    volumes: 
      - webpackBuild:/static/build
    ports:
      - "5000:5000"
    depends_on:
      - webpack
    networks:
      - container-network
    command: ["./wait-for-it.sh", "http://webpack:2992", "-t", "15", "--", "bash", "/app/start.sh"]
  
volumes: 
  webpackBuild:
    external: false

networks:
  container-network:
